### PR TITLE
Add radial progress bar

### PR DESCRIPTION
**Pull request by aaronliu0130**
See conversation in #858

w/o primary under halloween
w/o primary under corporation
w/ primary under halloween
w/ primary under corporation

## Summary by CodeRabbit

- **Refactor**
  - Improved the rendering logic for the progress bar display for better performance and readability.
  - Enhanced the conditional rendering of progress messages, ensuring more accurate and user-friendly display.

### CODE REVIEW

**Comment by aaronliu0130** [comment]
image
image
image

**Comment by aaronliu0130** [comment]
@NayamAmarshe How about this? It's either the entire thing including the text is the primary color or nothing's the primary color. I feel like not making it primary has more unity anyways.

**Comment by NayamAmarshe** [comment]
I was thinking more of putting the animation inside the progress bar and letting the text show progress below the progress bar.

**Comment by aaronliu0130** [comment]
I feel like putting it in the center is better semantically, structurally, and aesthetically. That said, putting the progress % out and below should be relatively easy change, and you are free to edit this PR

**Comment by NayamAmarshe** [comment]
> I feel like putting it in the center is better semantically, structurally, and aesthetically. That said, putting the progress % out and below should be relatively easy change, and you are free to edit this PR

Sorry for not merging the PR. I've been so busy with work and upscayl cloud that I've had no time. I wish to finish all this pending work soon.

**Comment by aaronliu0130** [comment]
Yeah it's okay, I've been busy too

**Pull request merged**
