### PR TITLE
Issue templates!

### PR DESCRIPTION
**Pull request by aaronliu0130**
I saw a lot of unused labels and 3 duplicates came up so I decided to try and do this. tried my best to mimic the changelog flavor in the descriptions

### CODE REVIEW

**Comment by NayamAmarshe** [comment]
Thanks a lot Aaron! Is this ready to be merged?

**Comment by aaronliu0130** [comment]
I think so. Probably do take a look though.

**Comment by aaronliu0130** [comment]
Hi, is there anything blocking this?

**Comment by aaronliu0130** [comment]
Thanks!
I have a small question though. Why are we using "Eye in speech bubble representing anti-bullying campaign" for the alternatives section of the feature request template?

**Comment by NayamAmarshe** [comment]
> Thanks!
> I have a small question though. Why are we using "Eye in speech bubble representing anti-bullying campaign" for the alternatives section of the feature request template?

No reason other than I thought it fit haha

**Pull request merged**
