### PR TITLE
Add progressbar when upscaling image

### PR DESCRIPTION
**Pull request by dabucz**

### CODE REVIEW

**Comment by NayamAmarshe** [comment]
@aaronliu0130 We aren't supposed to merge requests without a proper review.

**Comment by aaronliu0130** [comment]
@NayamAmarshe I reviewed it in #856. The bar seemed to work when I reviewed this.

**Comment by NayamAmarshe** [comment]
> @NayamAmarshe I reviewed it in #856. The bar seemed to work when I reviewed this.

This PR only has 2 changes. The first is the p tag with the classes and the second is a default HTML progressbar, which we wouldn't wanna use.

We have daisyUI for the UI library and we would want to use their components. This PR was unfinished and I'd have given it a good review. 

Not to mention, the description is empty, there are no screenshots or videos and no discussions from the OP. I assume the OP is a beginner and I'd have loved to help them with the PR :)

**Comment by aaronliu0130** [comment]
I'm pretty sure that adding the `progress` class applies the DaisyUI styles as I tested that and recommended that in my review in #856. It's not unstyled HTML.

It was my fault for not realizing they removed the `progress-primary` class for some reason though. Would you like to give this a second chance?

w/o primary under halloween
w/o primary under corporation
w/ primary under halloween
w/ primary under corporation

**Comment by aaronliu0130** [comment]
Also, something that's always annoyed me is how CSS frameworks make you use classnames that represent styles instead of semantics, but I guess we're too far gone for that now :)

**Pull request merged**
