### PR TITLE
Platform-specific directory slashes

### LINKED ISSUE #233: Logs use "/" in front of file name even on windows
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

Logs from #229:
`COMMAND: -i C:\Users\Jessa\Downloads/pexels-artem-podrez-6941448-removebg-preview.png -o C:\Users\Jessa\Downloads/pexels-artem-podrez-6941448-removebg-preview_upscayl_4x_realesrgan-x4plus.png -s 4 -m C:\Users\Jessa\upscayl\resources\models -n realesrgan-x4plus -f png`
"Downloads/pexels-artem-podrez-6941448-removebg-preview.png"
"Downloads/pexels-artem-podrez-6941448-removebg-preview_upscayl_4x_realesrgan-x4plus.png"

### To Reproduce

1. Pirate Windows
2. Do development run
3. Upscayl any image

### Expected Behavior

"Downloads\pexels-artem-podrez-6941448-removebg-preview.png"
"Downloads\pexels-artem-podrez-6941448-removebg-preview_upscayl_4x_realesrgan-x4plus.png"

### Version/Commit Hash

3a0878c

### OS Specifics

I have reproduced this on 22H2 25300.1000 w/ RX 580

### PR DESCRIPTION
**Pull request by aaronliu0130**
Should fix #233.

I'm not sure what Upscayl's code style guide is. If there are any code style issues, feel free to edit!

### CODE REVIEW

**Comment by NayamAmarshe** [comment]
Thank you! I'll test this PR today and review it.

We currently have no code style guide as it's been just me and TGS963 working on this project. I did try to clean up the code but it's a bit messy haha

**Comment by NayamAmarshe** [comment]
@TGS963 If you have time, could you please review it?

**Review by TGS963 — APPROVED** [review]
Everything seems to be in order :)

**Comment by NayamAmarshe** [comment]
@aaronliu0130 You can merge :)

**Pull request merged**
